services:
  enzir_db:
    image: postgres
    restart: always
    container_name: enzir_db
    env_file:
      - .env
    ports:
      - "54032:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
  enzir_web:
    build: .
    restart: always
    container_name: enzir_web
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - enzir_db
    volumes:
      - .:/app
      - ./alembic/versions:/app/alembic/versions
    command: >
            sh -c "
            mkdir -p /app/alembic/versions &&
            sleep 5 &&
            alembic revision --autogenerate -m "migrations" &&
            alembic upgrade head &&
            uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload"

volumes:
  postgres_data: